export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const REMOVE_ACTIVITY = 'REMOVE_ACTIVITY';
export const EDIT_ACTIVITY = 'EDIT_ACTIVITY';
export const SET_ACTIVITIES = 'SET_ACTIVITIES';
export const SET_FILTER = 'SET_FILTER';
